#!/usr/bin/python3
import bs4,requests
#filed = open(requests.get('https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India'))
new_file = open('html_google.html')
bs_obj=bs4.BeautifulSoup(new_file.read(),"html.parser")
print(bs_obj.find_all('img',_class="rg_ic"))
#print(bs_obj.p)
#print(bs_obj.p.string)
#print(type(str(requests.get('https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India'))))
#print(type(filed))
#print(type(filed.read()))
#filed=requests.get('https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India').text
#soup = bs4.BeautifulSoup(filed,"lxml")
#elems = soup.select('#authorx')
#print(elems[0].getText())
#print(soup.prettify()[:300])
#new_list=('\n'.split((soup.prettify())))
#print(soup.title.string)
#print(soup.a)
#print(soup.find_all("a"))
#all_links=soup.find_all("a")
#for link in all_links:
#	print(link.get("href"))
#tabs=soup.find_all('table')
#correct_table = soup.find('table',class_='wikitable sortable plainrowheaders')
#correct_table = soup.find_all('table',class_='class="wikitable sortable plainrowheaders jquery-tablesorter"')
#print(correct_table[:100])
#print('\n'.split(str((soup.find_all("a")))))
#print((requests.get('https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India')).text)
